name = "MLDataPattern"
uuid = "9920b226-0b2a-5f5f-9153-9aa70a013f8b"
authors = ["Christof Stocker <stocker.christof@gmail.com>"]
version = "0.5.4"

[deps]
LearnBase = "7f8f8fb0-2700-5f03-b4bd-41f8cfc144b6"
MLLabelUtils = "66a33bbf-0c2b-5fc8-a008-9da813334f0a"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
DataFrames = "0.20, 0.21"
LearnBase = "0.2, 0.3, 0.4"
MLLabelUtils = "0.4, 0.5"
StatsBase = "0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.30, 0.31, 0.32, 0.33"
julia = "0.7, 1"

[extras]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
ReferenceTests = "324d217c-45ce-50fc-942e-d289b448e8cf"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["DataFrames", "Random", "ReferenceTests", "SparseArrays", "Test"]
