name = "MLDataPattern"
uuid = "9920b226-0b2a-5f5f-9153-9aa70a013f8b"

[deps]
LearnBase = "7f8f8fb0-2700-5f03-b4bd-41f8cfc144b6"
MLLabelUtils = "66a33bbf-0c2b-5fc8-a008-9da813334f0a"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
LearnBase = "~0.2.0"
MLLabelUtils = "≥ 0.4.0"
StatsBase = "≥ 0.24.0"
julia = "0.7, 1"

[extras]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
ReferenceTests = "324d217c-45ce-50fc-942e-d289b448e8cf"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "SparseArrays", "Random", "ReferenceTests"]
